### ISSUE TITLE
Elasticsearch trial does not run

### ISSUE THREAD

**Issue by avgKol** [thestormforge/examples#34]
The elasticsearch trial does not run.

The controller logs an error 

` {"level":"error","ts":1609808467.7702744,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"experiment","request":"default/elasticsearch-example","error":"trials.redskyops.dev \"elasticsearch-example-467kp\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/Users/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88"}`

The elasticsearch-example-9lldj-create-6w8fk pod that was created by the trial logs this error

`Error: exit status 1
Usage:
  HelmGenerator FILE [flags]

Flags:
  -h, --help   help for HelmGenerator

Error: failure in plugin configured via /tmp/kust-plugin-config-890057429; exit status 1: exit status 1
error: no objects passed to create`

**Comment by bradbeam** [comment]
Thanks for the report. Can you provide the controller version? `redskyctl version`

**Comment by avgKol** [comment]
This seems to be a dns resolution error on the nodes.
