### ISSUE TITLE
Error using kustomize when trying quick start

### ISSUE THREAD

**Issue by liko9** [thestormforge/examples#66]
When following this section:  https://docs.stormforge.io/optimize/getting-started/quickstart/#create-the-experiment

I receive the following error:
`kustomize build github.com/thestormforge/examples/postgres
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/tmp/kustomize-455607605/postgres'`

kustomize version: `{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}`

**Comment by thecrudge** [comment]
Yea, we need to fix the docs. If you have stormforge installed, you can just apply the experiment.yaml

**Comment by thecrudge** [comment]
Closing issue - fixed docs
